"""action tracking fields on email_processing

Revision ID: 7f22a41fa827
Revises: d370a2574f79
Create Date: 2026-09-09 11:20:41.351225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f22a41fa827'
down_revision: Union[str, Sequence[str], None] = 'd370a2574f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    server_default is required on every NOT NULL column added here: SQLite
    rejects a NOT NULL ADD COLUMN with no default on a non-empty table, and
    this table already has rows from real runs. user_action_status defaults to
    PENDING rather than an empty string so pre-existing actionable emails (from
    before this feature existed) surface in the dashboard's open-actions view
    instead of silently vanishing.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_processing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('why_it_matters', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('suggested_deadline', sa.String(length=128), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('suggested_reply', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('user_action_status', sa.String(length=16), nullable=False, server_default='PENDING'))
        batch_op.add_column(sa.Column('user_action_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('user_action_note', sa.Text(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_processing', schema=None) as batch_op:
        batch_op.drop_column('user_action_note')
        batch_op.drop_column('user_action_at')
        batch_op.drop_column('user_action_status')
        batch_op.drop_column('suggested_reply')
        batch_op.drop_column('suggested_deadline')
        batch_op.drop_column('why_it_matters')

    # ### end Alembic commands ###
