"""initial schema

Revision ID: d370a2574f79
Revises: 
Create Date: 2026-09-07 23:36:38.933690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd370a2574f79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_run_id'), ['run_id'], unique=False)

    op.create_table('automation_run',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_date', name='uq_automation_run_date')
    )
    with op.batch_alter_table('automation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_run_run_date'), ['run_date'], unique=False)

    op.create_table('email_processing',
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('requires_reply', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.String(length=32), nullable=False),
    sa.Column('action_applied', sa.String(length=32), nullable=False),
    sa.Column('action_reason', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('email_processing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_processing_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_processing_thread_id'), ['thread_id'], unique=False)

    op.create_table('occasion_send_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_year', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'recipient_email', 'event_year', name='uq_occasion_send_identity')
    )
    with op.batch_alter_table('occasion_send_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occasion_send_log_run_id'), ['run_id'], unique=False)

    op.create_table('agent_execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['automation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'agent_name', name='uq_agent_execution_run_agent')
    )
    with op.batch_alter_table('agent_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_execution_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_execution_run_id'))

    op.drop_table('agent_execution')
    with op.batch_alter_table('occasion_send_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occasion_send_log_run_id'))

    op.drop_table('occasion_send_log')
    with op.batch_alter_table('email_processing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_processing_thread_id'))
        batch_op.drop_index(batch_op.f('ix_email_processing_run_id'))

    op.drop_table('email_processing')
    with op.batch_alter_table('automation_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_run_run_date'))

    op.drop_table('automation_run')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_run_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
